### ISSUE TITLE
«Call to a member function getProductUrl() on null in app/design/frontend/MageSuper/magestylish/Magento_Sales/templates/order/items/renderer/default.phtml:14»

### ISSUE THREAD

**Issue by dmitry-fedyuk** [canadasatellite-ca/site#182]
```
[
    {
        "mage2pro/core": "7.6.1",
        "Magento": "2.3.5-p2",
        "PHP": "7.2.34-8+ubuntu16.04.1+deb.sury.org+1",
        "IP Address": "61.74.85.150",
        "Referer": "https://www.asiasatellite.co/customer/account/",
        "Request Method": "GET",
        "URL": "https://www.asiasatellite.co/sales/order/view/order_id/53263/",
        "User-Agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Mobile/15E148 Safari/604.1"
    }
]
************************************
[E_ERROR] Uncaught Error: Call to a member function getProductUrl() on null in app/design/frontend/MageSuper/magestylish/Magento_Sales/templates/order/items/renderer/default.phtml
Stack trace:
#0 vendor/magento/framework/View/TemplateEngine/Php.php(59): include()
#1 vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Sales\Block\Order\Item\Renderer\DefaultRenderer\Interceptor), '/var/www/sites/...', Array)
#2 vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callParent('render', Array)
#3 vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\TemplateEngine\Php\Interceptor->Magento\Framework\Interception\{clo
File: var/view_preprocessed/pub/static/app/design/frontend/MageSuper/magestylish/Magento_Sales/templates/order/items/renderer/default.phtml
Line: 1
```

**Comment by dmitry-fedyuk** [comment]
```
[
    {
        "mage2pro/core": "7.5.9",
        "Magento": "2.3.5-p2",
        "PHP": "7.2.34-8+ubuntu16.04.1+deb.sury.org+1",
        "IP Address": "69.168.163.81",
        "Referer": "https://www.canadasatellite.ca/sales/order/history/",
        "Request Method": "GET",
        "URL": "https://www.canadasatellite.ca/sales/order/view/order_id/49018/",
        "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15"
    }
]
************************************
[E_ERROR] Uncaught Error: Call to a member function getProductUrl() on null in var/view_preprocessed/pub/static/app/design/frontend/MageSuper/magestylish/Magento_Sales/templates/order/items/renderer/default.phtml:1
Stack trace:
#0 vendor/magento/framework/View/TemplateEngine/Php.php(59): include()
#1 vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Sales\Block\Order\Item\Renderer\DefaultRenderer\Interceptor), '/var/www/sites/...', Array)
#2 vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callParent('render', Array)
#3 vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\TemplateEngine\Php\Interceptor->Magento\Framework\Interception\{clo
File: var/view_preprocessed/pub/static/app/design/frontend/MageSuper/magestylish/Magento_Sales/templates/order/items/renderer/default.phtml
Line: 1
```
