### ISSUE TITLE
«Call to a member function toHtml() on boolean in app/code/Interactivated/Quotecheckout/Controller/Index/Save.php:629»

### ISSUE THREAD

**Issue by dmitry-fedyuk** [canadasatellite-ca/site#222]
```
[
    {
        "mage2pro/core": "7.7.1",
        "Magento": "2.3.5-p2",
        "PHP": "7.2.34-8+ubuntu16.04.1+deb.sury.org+1",
        "IP Address": "37.19.213.49",
        "Referer": "https://www.canadasatellite.ca/quotecheckout/",
        "Request Method": "POST",
        "URL": "https://www.canadasatellite.ca/quotecheckout/index/save/",
        "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Safari/605.1.15",
        "Post": {
            "form_key": "L8cJ1frOq3yYLWZW",
            "billing_address_id": "48987",
            "billing": {
                "address_id": "451229",
                "email": "cbball@me.com",
                "firstname": "CB",
                "lastname": "Ball",
                "company": "",
                "street": [
                    "589 Kingswood Pl",
                    "",
                    ""
                ],
                "city": "Burlington",
                "region_id": "74",
                "region": "",
                "postcode": "L7T 2W6",
                "country_id": "CA",
                "telephone": "6479992320"
            },
            "ship_to_same_address": "1",
            "shipping_address_id": "48987",
            "shipping": {
                "address_id": "451230",
                "firstname": "CB",
                "lastname": "Ball",
                "company": "",
                "street": [
                    "589 Kingswood Pl",
                    "",
                    ""
                ],
                "city": "Burlington",
                "region_id": "74",
                "region": "",
                "postcode": "L7T 2W6",
                "country_id": "CA",
                "telephone": "6479992320"
            },
            "cart": {
                "118051": {
                    "qty": "1"
                },
                "118052": {
                    "qty": "1"
                }
            },
            "onestepcheckout_comments": "",
            "subscribe_newsletter": "1",
            "updates": "{\"removeproduct\":true,\"updateshippingtype\":true,\"updatepaymenttype\":true,\"updatepaymentmethod\":true,\"addition_post\":{\"id\":\"118052\",\"hasgiftbox\":1},\"loader\":[\"checkout-shipping-method-load\",\"co-payment-form\",\"co-payment-form\",\"checkout-review-load\"]}",
            "id": "118052",
            "hasgiftbox": "1",
            "isAjax": "1"
        }
    }
]
************************************
[E_ERROR] Uncaught Error: Call to a member function toHtml() on boolean in app/code/Interactivated/Quotecheckout/Controller/Index/Save.php:629
Stack trace:
#0 app/code/Interactivated/Quotecheckout/Controller/Index/Save.php(189): Interactivated\Quotecheckout\Controller\Index\Save->renderGiftbox()
#1 app/code/Interactivated/Quotecheckout/Controller/Index/Save.php(55): Interactivated\Quotecheckout\Controller\Index\Save->_removeproduct()
#2 vendor/magento/framework/Interception/Interceptor.php(58): Interactivated\Quotecheckout\Controller\Index\Save->execute()
#3 vendor/magento/framework/Interception/Interceptor.php(138): Interactivated\Quotecheckout\Controller\Index\Save\Interceptor->___callParent('execute', Array)
#4 vendor/magento/framework/Interception/Interceptor.ph
File: app/code/Interactivated/Quotecheckout/Controller/Index/Save.php
Line: 629
```

**Comment by dmitry-fedyuk** [comment]
A duplicate of https://github.com/canadasatellite-ca/site/issues/141
