### ISSUE TITLE
`MageWorx_OrderEditor`: «Call to a member function getParentItem() on null in vendor/magento/module-bundle/Block/Adminhtml/Sales/Order/Items/Renderer.php:87»

### ISSUE THREAD

**Issue by dmitry-fedyuk** [canadasatellite-ca/site#236]
Related to https://github.com/canadasatellite-ca/site/issues/235

```
[
    {
        "mage2pro/core": "7.7.7",
        "Magento": "2.3.5-p2",
        "PHP": "7.2.34",
        "IP Address": "158.181.235.66",
        "Referer": "https://localhost.com:2216/admin_1st8gu/sales/order/view/order_id/54512",
        "Request Method": "GET",
        "URL": "https://localhost.com:2216/admin_1st8gu/sales/order_invoice/view/invoice_id/19675/",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36"
    }
]
************************************
[E_ERROR] Uncaught Error: Call to a member function getParentItem() on null in vendor\magento\module-bundle\Block\Adminhtml\Sales\Order\Items\Renderer.php:87
Stack trace:
#0 generated\code\Magento\Bundle\Block\Adminhtml\Sales\Order\Items\Renderer\Interceptor.php(37): Magento\Bundle\Block\Adminhtml\Sales\Order\Items\Renderer->getChildren(Object(Magento\Sales\Model\Order\Invoice\Item\Interceptor))
#1 vendor\magento\module-bundle\view\adminhtml\templates\sales\invoice\view\items\renderer.phtml(16): Magento\Bundle\Block\Adminhtml\Sales\Order\Items\Renderer\Interceptor->getChildren(Object(Magento\Sales\Model\Order\Invoice\Item\Interceptor))
#2 vendor\magento\framework\View\TemplateEngine\Php.php(59): include('C:\\work\\clients...')
#3 vendor\magento\framework\Inte
File: vendor\magento\module-bundle\Block\Adminhtml\Sales\Order\Items\Renderer.php
Line: 87
```

**Comment by dmitry-fedyuk** [comment]
![Uploading 02.png…]()

**Comment by dmitry-fedyuk** [comment]
## How to reproduce
1. Create an order on the frontend
2. Create the order's invoice in the backend
3. Delete an item from the order via the `MageWorx_OrderEditor` module.
4. Open the invoice in the backend.
