### ISSUE TITLE
`MageSuper_Casat`: «You just catched on trying to change product name and(or) description for not default store» on `bin/magento product:bundle:resave`

### ISSUE THREAD

**Issue by dmitry-fedyuk** [canadasatellite-ca/site#27]
```
#0 vendor/magento/framework/Event/Invoker/InvokerDefault.php(88): MageSuper\Casat\Observer\ProductSaveBefore->execute(Object(Magento\Framework\Event\Observer))
#1 vendor/magento/framework/Event/Invoker/InvokerDefault.php(74): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(MageSuper\Casat\Observer\ProductSaveBefore), Object(Magento\Framework\Event\Observer))
#2 vendor/magento/framework/Event/Manager.php(66): Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, Object(Magento\Framework\Event\Observer))
#3 generated/code/Magento/Framework/Event/Manager/Proxy.php(95): Magento\Framework\Event\Manager->dispatch('catalog_product...', Array)
#4 vendor/magento/framework/Model/AbstractModel.php(702): Magento\Framework\Event\Manager\Proxy->dispatch('catalog_product...', Array)
#5 vendor/magento/module-catalog/Model/AbstractModel.php(383): Magento\Framework\Model\AbstractModel->beforeSave()
#6 vendor/magento/module-catalog/Model/Product.php(933): Magento\Catalog\Model\AbstractModel->beforeSave()
#7 vendor/magento/framework/EntityManager/Observer/BeforeEntitySave.php(34): Magento\Catalog\Model\Product->beforeSave()
#8 vendor/magento/framework/Event/Invoker/InvokerDefault.php(88): Magento\Framework\EntityManager\Observer\BeforeEntitySave->execute(Object(Magento\Framework\Event\Observer))
#9 vendor/magento/framework/Event/Invoker/InvokerDefault.php(74): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(Magento\Framework\EntityManager\Observer\BeforeEntitySave), Object(Magento\Framework\Event\Observer))
#10 vendor/magento/framework/Event/Manager.php(66): Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, Object(Magento\Framework\Event\Observer))
#11 generated/code/Magento/Framework/Event/Manager/Proxy.php(95): Magento\Framework\Event\Manager->dispatch('magento_catalog...', Array)
#12 vendor/magento/framework/EntityManager/EventManager.php(52): Magento\Framework\Event\Manager\Proxy->dispatch('magento_catalog...', Array)
#13 vendor/magento/framework/EntityManager/Operation/Update.php(106): Magento\Framework\EntityManager\EventManager->dispatchEntityEvent('Magento\Catalog...', 'save_before', Array)
#14 vendor/magento/framework/EntityManager/EntityManager.php(96): Magento\Framework\EntityManager\Operation\Update->execute(Object(LitExtension\Core\Model\Preference\Product\Product\Interceptor), Array)
#15 vendor/magento/module-catalog/Model/ResourceModel/Product.php(758): Magento\Framework\EntityManager\EntityManager->save(Object(LitExtension\Core\Model\Preference\Product\Product\Interceptor))
#16 vendor/magento/framework/Interception/Interceptor.php(58): Magento\Catalog\Model\ResourceModel\Product->save(Object(LitExtension\Core\Model\Preference\Product\Product\Interceptor))
#17 vendor/magento/framework/Interception/Interceptor.php(138): MageSuper\Casat\Model\ResourceModel\Product\Interceptor->___callParent('save', Array)
#18 vendor/mirasvit/module-search/src/Search/Model/ScoreRule/Indexer/Plugin/ProductPlugin.php(62): MageSuper\Casat\Model\ResourceModel\Product\Interceptor->Magento\Framework\Interception\{closure}(Object(LitExtension\Core\Model\Preference\Product\Product\Interceptor))
#19 vendor/mirasvit/module-search/src/Search/Model/ScoreRule/Indexer/Plugin/ProductPlugin.php(35): Mirasvit\Search\Model\ScoreRule\Indexer\Plugin\ProductPlugin->addCommitCallback(Object(MageSuper\Casat\Model\ResourceModel\Product\Interceptor), Object(Closure), Object(LitExtension\Core\Model\Preference\Product\Product\Interceptor))
#20 vendor/magento/framework/Interception/Interceptor.php(135): Mirasvit\Search\Model\ScoreRule\Indexer\Plugin\ProductPlugin->aroundSave(Object(MageSuper\Casat\Model\ResourceModel\Product\Interceptor), Object(Closure), Object(LitExtension\Core\Model\Preference\Product\Product\Interceptor))
#21 vendor/magento/module-catalog-search/Model/Indexer/Fulltext/Plugin/Product.php(58): MageSuper\Casat\Model\ResourceModel\Product\Interceptor->Magento\Framework\Interception\{closure}(Object(LitExtension\Core\Model\Preference\Product\Product\Interceptor))
#22 vendor/magento/module-catalog-search/Model/Indexer/Fulltext/Plugin/Product.php(28): Magento\CatalogSearch\Model\Indexer\Fulltext\Plugin\Product->addCommitCallback(Object(MageSuper\Casat\Model\ResourceModel\Product\Interceptor), Object(Closure), Object(LitExtension\Core\Model\Preference\Product\Product\Interceptor))
#23 vendor/magento/framework/Interception/Interceptor.php(135): Magento\CatalogSearch\Model\Indexer\Fulltext\Plugin\Product->aroundSave(Object(MageSuper\Casat\Model\ResourceModel\Product\Interceptor), Object(Closure), Object(LitExtension\Core\Model\Preference\Product\Product\Interceptor))
#24 vendor/magento/framework/App/Cache/FlushCacheByTags.php(69): MageSuper\Casat\Model\ResourceModel\Product\Interceptor->Magento\Framework\Interception\{closure}(Object(LitExtension\Core\Model\Preference\Product\Product\Interceptor))
#25 vendor/magento/framework/Interception/Interceptor.php(135): Magento\Framework\App\Cache\FlushCacheByTags->aroundSave(Object(MageSuper\Casat\Model\ResourceModel\Product\Interceptor), Object(Closure), Object(LitExtension\Core\Model\Preference\Product\Product\Interceptor))
#26 vendor/magento/framework/Interception/Interceptor.php(153): MageSuper\Casat\Model\ResourceModel\Product\Interceptor->Magento\Framework\Interception\{closure}(Object(LitExtension\Core\Model\Preference\Product\Product\Interceptor))
#27 generated/code/MageSuper/Casat/Model/ResourceModel/Product/Interceptor.php(273): MageSuper\Casat\Model\ResourceModel\Product\Interceptor->___callPlugins('save', Array, Array)
#28 vendor/magento/framework/Model/AbstractModel.php(655): MageSuper\Casat\Model\ResourceModel\Product\Interceptor->save(Object(LitExtension\Core\Model\Preference\Product\Product\Interceptor))
#29 app/code/CanadaSatellite/Theme/Console/BundleProductResave.php(71): Magento\Framework\Model\AbstractModel->save()
#30 vendor/symfony/console/Command/Command.php(255): CanadaSatellite\Theme\Console\BundleProductResave->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#31 vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#32 vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(CanadaSatellite\Theme\Console\BundleProductResave), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#33 vendor/magento/framework/Console/Cli.php(115): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#34 vendor/symfony/console/Application.php(149): Magento\Framework\Console\Cli->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#35 bin/magento(23): Symfony\Component\Console\Application->run()
#36 {main}
```

**Comment by dmitry-fedyuk** [comment]
The `product:bundle:resave` command is run by `/var/spool/cron/crontabs/www-data`
