### ISSUE TITLE
«preg_match() expects parameter 2 to be string, object given in vendor/magento/module-catalog/Helper/Output.php:245»

### ISSUE THREAD

**Issue by dmitry-fedyuk** [canadasatellite-ca/site#28]
```
[
    {
        "mage2pro/core": "7.2.1",
        "Magento": "2.3.5-p2",
        "PHP": "7.2.34-8+ubuntu16.04.1+deb.sury.org+1",
        "Referer": null,
        "URL": "https://www.canadasatellite.ca/compare/Iridium-9523-Core-Module/Iridium-9602-SBD-Transceiver/Iridium-Edge-SBD-Modem/Iridium-9603N-SBD-Transceiver/Iridium-Certus-9770-Transceiver/Iridium-Certus-9810-Transceiver/Iridium-AssetPack-3-AP3/Iridium-Edge-Pro-SBD-Modem/Iridium-Edge-Solar-SBD-Modem"
    }
]
************************************
[E_ERROR] Uncaught TypeError: preg_match() expects parameter 2 to be string, object given in vendor/magento/module-catalog/Helper/Output.php:245
Stack trace:
#0 vendor/magento/module-catalog/Helper/Output.php(245): preg_match('/{{([a-z]{0,10}...', Object(Magento\Framework\Phrase))
#1 vendor/magento/module-catalog/Helper/Output.php(185): Magento\Catalog\Helper\Output->isDirectivesExists(Object(Magento\Framework\Phrase))
#2 var/view_preprocessed/pub/static/app/design/frontend/MageSuper/magestylish/Magento_Catalog/templates/product/compare/list.phtml(1): Magento\Catalog\Helper\Output->productAttribute(Object(LitExtension\Core\Model\Preference\Product\Product\Interceptor), Object(Magento\Framework\Phrase), 'short_descripti...')
#3 vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/var/www/sites/
File: vendor/magento/module-catalog/Helper/Output.php
Line: 245
```

**Comment by dmitry-fedyuk** [comment]
It is a Magento 2 core bug: https://github.com/magento/magento2/issues/28254
