### ISSUE TITLE
«Call to a member function getAdditionalInformation() on null in vendor/magento/module-sales/Model/OrderRepository.php:183»

### ISSUE THREAD

**Issue by dmitry-fedyuk** [canadasatellite-ca/site#29]
```
[
    {
        "mage2pro/core": "7.2.1",
        "Magento": "2.3.5-p2",
        "PHP": "7.2.34-8+ubuntu16.04.1+deb.sury.org+1",
        "Referer": "https://www.canadasatellite.ca/customer/account/login/",
        "URL": "https://www.canadasatellite.ca/customer/account/index/"
    }
]
************************************
[E_ERROR] Uncaught Error: Call to a member function getAdditionalInformation() on null in vendor/magento/module-sales/Model/OrderRepository.php:183
Stack trace:
#0 vendor/magento/module-sales/Model/OrderRepository.php(145): Magento\Sales\Model\OrderRepository->setPaymentAdditionalInfo(Object(Magento\Sales\Model\Order\Interceptor))
#1 vendor/magento/framework/Interception/Interceptor.php(58): Magento\Sales\Model\OrderRepository->get('30700')
#2 vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Model\OrderRepository\Interceptor->___callParent('get', Array)
#3 vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Model\OrderRepository\Interceptor->Magento\Framework\Interception\{closure}('30700')
#4 generated/code/Magento/Sal
File: vendor/magento/module-sales/Model/OrderRepository.php
Line: 183
```

**Comment by dmitry-fedyuk** [comment]
![01](https://user-images.githubusercontent.com/83204/111906272-eefa7780-8a79-11eb-8907-a59deb5aaac9.png)

![Uploading 02.png…]()

**Comment by dmitry-fedyuk** [comment]
It seems that the website was incorrectly migrated to Magento 2 from another shopping cart, and order with ID < 32655 does not have associated records in the `sales_order_payment` table.
