### ISSUE TITLE
«Call to a member function setProductItem() on boolean in app/design/frontend/MageSuper/magestylish/Magento_Sales/templates/order/items.phtml:37» on printing an order by a customer

### ISSUE THREAD

**Issue by dmitry-fedyuk** [canadasatellite-ca/site#32]
```
[
    {
        "mage2pro/core": "7.2.1",
        "Magento": "2.3.5-p2",
        "PHP": "7.2.34-8+ubuntu16.04.1+deb.sury.org+1",
        "Referer": "https://www.canadasatellite.ca/checkout/onepage/success/",
        "URL": "https://www.canadasatellite.ca/sales/order/print/order_id/52161/"
    }
]
************************************
[E_ERROR] Uncaught Error: Call to a member function setProductItem() on boolean in var/view_preprocessed/pub/static/app/design/frontend/MageSuper/magestylish/Magento_Sales/templates/order/items.phtml:1
Stack trace:
#0 vendor/magento/framework/View/TemplateEngine/Php.php(59): include()
#1 vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Sales\Block\Order\Items\Interceptor), '/var/www/sites/...', Array)
#2 vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callParent('render', Array)
#3 vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\TemplateEngine\Php\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Sales\Block\Orde
File: var/view_preprocessed/pub/static/app/design/frontend/MageSuper/magestylish/Magento_Sales/templates/order/items.phtml
Line: 1
```

**Comment by dmitry-fedyuk** [comment]
![02](https://user-images.githubusercontent.com/83204/112066942-71298f80-8b91-11eb-9551-2844d102ffba.png)

**Comment by dmitry-fedyuk** [comment]
It is related to the absent `catalog.product.top.list.mageworx.downloads.attachments` block.
