### ISSUE TITLE
«Could not save child: "Unknown entity type: Magento\Bundle\Model\Selection\Interceptor requested"» on `bin/magento product:bundle:resave`

### ISSUE THREAD

**Issue by dmitry-fedyuk** [canadasatellite-ca/site#44]
```
{
    "channel": "main",
    "datetime": {
        "date": "2021-03-20 06:15:06.288980",
        "timezone_type": 3,
        "timezone": "UTC"
    },
    "level": 400,
    "level_name": "ERROR",
    "Mage2.PRO": [
        {
            "Command": "bin/magento product:bundle:resave --Id=5326",
            "mage2pro/core": "7.2.1",
            "Magento": "2.3.5-p2",
            "PHP": "7.2.34-8+ubuntu16.04.1+deb.sury.org+1"
        }
    ],
    "message": "Could not save child: \"Unknown entity type: Magento\Bundle\Model\Selection\Interceptor requested\"
#0 vendor/magento/framework/Interception/Interceptor.php(135): CanadaSatellite\Theme\Plugin\Model\LinkManagement->aroundSaveChild(Object(Magento\Bundle\Model\LinkManagement\Interceptor), Object(Closure), 'Bell-TV-6400-HD...', Object(Magento\Bundle\Model\Link\Interceptor))
#1 vendor/magento/framework/Interception/Interceptor.php(153): Magento\Bundle\Model\LinkManagement\Interceptor->Magento\Framework\Interception\{closure}('Bell-TV-6400-HD...', Object(Magento\Bundle\Model\Link\Interceptor))
#2 generated/code/Magento/Bundle/Model/LinkManagement/Interceptor.php(26): Magento\Bundle\Model\LinkManagement\Interceptor->___callPlugins('saveChild', Array, NULL)
#3 vendor/magento/module-bundle/Model/Option/SaveAction.php(148): Magento\Bundle\Model\LinkManagement\Interceptor->saveChild('Bell-TV-6400-HD...', Object(Magento\Bundle\Model\Link\Interceptor))
#4 vendor/magento/module-bundle/Model/Option/SaveAction.php(102): Magento\Bundle\Model\Option\SaveAction->updateOptionSelection(Object(LitExtension\Core\Model\Preference\Product\Product\Interceptor), Object(Magento\Bundle\Model\Option\Interceptor))
#5 vendor/magento/module-bundle/Model/Product/SaveHandler.php(132): Magento\Bundle\Model\Option\SaveAction->save(Object(LitExtension\Core\Model\Preference\Product\Product\Interceptor), Object(Magento\Bundle\Model\Option\Interceptor))
#6 vendor/magento/module-bundle/Model/Product/SaveHandler.php(90): Magento\Bundle\Model\Product\SaveHandler->saveOptions(Object(LitExtension\Core\Model\Preference\Product\Product\Interceptor), Array, Array)
#7 vendor/magento/framework/EntityManager/Operation/Update/UpdateExtensions.php(49): Magento\Bundle\Model\Product\SaveHandler->execute(Object(LitExtension\Core\Model\Preference\Product\Product\Interceptor), Array)
#8 vendor/magento/framework/EntityManager/Operation/Update.php(109): Magento\Framework\EntityManager\Operation\Update\UpdateExtensions->execute(Object(LitExtension\Core\Model\Preference\Product\Product\Interceptor), Array)
#9 vendor/magento/framework/EntityManager/EntityManager.php(96): Magento\Framework\EntityManager\Operation\Update->execute(Object(LitExtension\Core\Model\Preference\Product\Product\Interceptor), Array)
#10 vendor/magento/module-catalog/Model/ResourceModel/Product.php(758): Magento\Framework\EntityManager\EntityManager->save(Object(LitExtension\Core\Model\Preference\Product\Product\Interceptor))
#11 vendor/magento/framework/Interception/Interceptor.php(58): Magento\Catalog\Model\ResourceModel\Product->save(Object(LitExtension\Core\Model\Preference\Product\Product\Interceptor))
#12 vendor/magento/framework/Interception/Interceptor.php(138): MageSuper\Casat\Model\ResourceModel\Product\Interceptor->___callParent('save', Array)
#13 vendor/mirasvit/module-search/src/Search/Model/ScoreRule/Indexer/Plugin/ProductPlugin.php(62): MageSuper\Casat\Model\ResourceModel\Product\Interceptor->Magento\Framework\Interception\{closure}(Object(LitExtension\Core\Model\Preference\Product\Product\Interceptor))
#14 vendor/mirasvit/module-search/src/Search/Model/ScoreRule/Indexer/Plugin/ProductPlugin.php(35): Mirasvit\Search\Model\ScoreRule\Indexer\Plugin\ProductPlugin->addCommitCallback(Object(MageSuper\Casat\Model\ResourceModel\Product\Interceptor), Object(Closure), Object(LitExtension\Core\Model\Preference\Product\Product\Interceptor))
#15 vendor/magento/framework/Interception/Interceptor.php(135): Mirasvit\Search\Model\ScoreRule\Indexer\Plugin\ProductPlugin->aroundSave(Object(MageSuper\Casat\Model\ResourceModel\Product\Interceptor), Object(Closure), Object(LitExtension\Core\Model\Preference\Product\Product\Interceptor))
#16 vendor/magento/module-catalog-search/Model/Indexer/Fulltext/Plugin/Product.php(58): MageSuper\Casat\Model\ResourceModel\Product\Interceptor->Magento\Framework\Interception\{closure}(Object(LitExtension\Core\Model\Preference\Product\Product\Interceptor))
#17 vendor/magento/module-catalog-search/Model/Indexer/Fulltext/Plugin/Product.php(28): Magento\CatalogSearch\Model\Indexer\Fulltext\Plugin\Product->addCommitCallback(Object(MageSuper\Casat\Model\ResourceModel\Product\Interceptor), Object(Closure), Object(LitExtension\Core\Model\Preference\Product\Product\Interceptor))
#18 vendor/magento/framework/Interception/Interceptor.php(135): Magento\CatalogSearch\Model\Indexer\Fulltext\Plugin\Product->aroundSave(Object(MageSuper\Casat\Model\ResourceModel\Product\Interceptor), Object(Closure), Object(LitExtension\Core\Model\Preference\Product\Product\Interceptor))
#19 vendor/magento/framework/App/Cache/FlushCacheByTags.php(69): MageSuper\Casat\Model\ResourceModel\Product\Interceptor->Magento\Framework\Interception\{closure}(Object(LitExtension\Core\Model\Preference\Product\Product\Interceptor))
#20 vendor/magento/framework/Interception/Interceptor.php(135): Magento\Framework\App\Cache\FlushCacheByTags->aroundSave(Object(MageSuper\Casat\Model\ResourceModel\Product\Interceptor), Object(Closure), Object(LitExtension\Core\Model\Preference\Product\Product\Interceptor))
#21 vendor/magento/framework/Interception/Interceptor.php(153): MageSuper\Casat\Model\ResourceModel\Product\Interceptor->Magento\Framework\Interception\{closure}(Object(LitExtension\Core\Model\Preference\Product\Product\Interceptor))
#22 generated/code/MageSuper/Casat/Model/ResourceModel/Product/Interceptor.php(39): MageSuper\Casat\Model\ResourceModel\Product\Interceptor->___callPlugins('save', Array, Array)
#23 vendor/magento/framework/Model/AbstractModel.php(655): MageSuper\Casat\Model\ResourceModel\Product\Interceptor->save(Object(LitExtension\Core\Model\Preference\Product\Product\Interceptor))
#24 app/code/CanadaSatellite/Theme/Console/BundleProductResave.php(71): Magento\Framework\Model\AbstractModel->save()
#25 vendor/symfony/console/Command/Command.php(255): CanadaSatellite\Theme\Console\BundleProductResave->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(CanadaSatellite\Theme\Console\BundleProductResave), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 vendor/magento/framework/Console/Cli.php(115): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#29 vendor/symfony/console/Application.php(149): Magento\Framework\Console\Cli->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#30 bin/magento(23): Symfony\Component\Console\Application->run()
#31 {main}"
}
Location:    vendor/mage2pro/core/Framework/Logger/Handler.php:55
Callee:      df_log_l
*****************1******************
Location:    vendor/monolog/monolog/src/Monolog/Logger.php:344
Callee:      Df\Framework\Logger\Handler::handle
*****************2******************
Location:    vendor/magento/framework/Logger/Monolog.php:48
Callee:      Monolog\Logger::addRecord
*****************3******************
Location:    vendor/monolog/monolog/src/Monolog/Logger.php:712
Callee:      Magento\Framework\Logger\Monolog::addRecord
*****************4******************
Location:    vendor/magento/framework/Console/Cli.php:118
Callee:      Monolog\Logger::error
*****************5******************
Location:    vendor/symfony/console/Application.php:149
Callee:      Magento\Framework\Console\Cli::doRun
*****************6******************
Location:    bin/magento:23
Callee:      Symfony\Component\Console\Application::run
```

**Comment by dmitry-fedyuk** [comment]
![03](https://user-images.githubusercontent.com/83204/112518027-35760c00-8dc3-11eb-9a13-d35646ce7edf.png)

**Comment by dmitry-fedyuk** [comment]
A similar issue: https://github.com/mage2pro/ipay88/issues/17
