### ISSUE TITLE
«NOT_FOUND - no queue 'async.operations.all' in vhost '/'»

### ISSUE THREAD

**Issue by dmitry-fedyuk** [canadasatellite-ca/site#48]
```
{
    "channel": "main",
    "datetime": {
        "date": "2021-03-26 20:25:05.934550",
        "timezone_type": 3,
        "timezone": "UTC"
    },
    "level": 400,
    "level_name": "ERROR",
    "Mage2.PRO": [
        {
            "Command": "bin/magento queue:consumers:start async.operations.all --single-thread --max-messages=10000",
            "mage2pro/core": "7.2.6",
            "Magento": "2.3.5-p2",
            "PHP": "7.2.34-8+ubuntu16.04.1+deb.sury.org+1"
        }
    ],
    "message": "NOT_FOUND - no queue 'async.operations.all' in vhost '/'
#0 [internal function]: PhpAmqpLib\Channel\AMQPChannel->channel_close(Object(PhpAmqpLib\Wire\AMQPReader))
#1 vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(213): call_user_func(Array, Object(PhpAmqpLib\Wire\AMQPReader))
#2 vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(371): PhpAmqpLib\Channel\AbstractChannel->dispatch('20,40', '\x01\x948NOT_FOUND - ...', NULL)
#3 vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php(1065): PhpAmqpLib\Channel\AbstractChannel->wait(Array, false, 0)
#4 vendor/magento/framework-amqp/Queue.php(75): PhpAmqpLib\Channel\AMQPChannel->basic_get('async.operation...')
#5 vendor/magento/framework-message-queue/CallbackInvoker.php(66): Magento\Framework\Amqp\Queue->dequeue()
#6 vendor/magento/module-asynchronous-operations/Model/MassConsumer.php(78): Magento\Framework\MessageQueue\CallbackInvoker->invoke(Object(Magento\Framework\Amqp\Queue), '10000', Object(Closure))
#7 vendor/magento/module-message-queue/Console/StartConsumerCommand.php(94): Magento\AsynchronousOperations\Model\MassConsumer->process('10000')
#8 vendor/symfony/console/Command/Command.php(255): Magento\MessageQueue\Console\StartConsumerCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 generated/code/Magento/MessageQueue/Console/StartConsumerCommand/Proxy.php(143): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 vendor/symfony/console/Application.php(1009): Magento\MessageQueue\Console\StartConsumerCommand\Proxy->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Magento\MessageQueue\Console\StartConsumerCommand\Proxy), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 vendor/magento/framework/Console/Cli.php(115): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 vendor/symfony/console/Application.php(149): Magento\Framework\Console\Cli->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 bin/magento(23): Symfony\Component\Console\Application->run()
#15 {main}"
}
Location:    vendor/mage2pro/core/Framework/Logger/Handler.php:55
Callee:      df_log_l
*****************1******************
Location:    vendor/monolog/monolog/src/Monolog/Logger.php:344
Callee:      Df\Framework\Logger\Handler::handle
*****************2******************
Location:    vendor/magento/framework/Logger/Monolog.php:48
Callee:      Monolog\Logger::addRecord
*****************3******************
Location:    vendor/monolog/monolog/src/Monolog/Logger.php:712
Callee:      Magento\Framework\Logger\Monolog::addRecord
*****************4******************
Location:    vendor/magento/framework/Console/Cli.php:118
Callee:      Monolog\Logger::error
*****************5******************
Location:    vendor/symfony/console/Application.php:149
Callee:      Magento\Framework\Console\Cli::doRun
*****************6******************
Location:    bin/magento:23
Callee:      Symfony\Component\Console\Application::run
```

**Comment by dmitry-fedyuk** [comment]
The same as https://github.com/tradefurniturecompany/server/issues/7

**Comment by dmitry-fedyuk** [comment]
Fixed by `bin/magento setup:upgrade`: https://github.com/tradefurniturecompany/server/issues/7#issuecomment-585414187
