### ISSUE TITLE
`MageWorx_Downloads`: «Call to a member function setProductItem() on boolean» in `app/design/frontend/MageSuper/magestylish/Magento_Sales/templates/order/items.phtml:37` on `POST` to `sales/guest/form`

### ISSUE THREAD

**Issue by dmitry-fedyuk** [canadasatellite-ca/site#61]
Similar to https://github.com/canadasatellite-ca/site/issues/32

```
[
    {
        "mage2pro/core": "7.2.6",
        "Magento": "2.3.5-p2",
        "PHP": "7.2.34-8+ubuntu16.04.1+deb.sury.org+1",
        "Referer": "https://www.canadasatellite.ca/sales/guest/form/",
        "URL": "https://www.canadasatellite.ca/sales/guest/view/",
        "Post": {
            "oar_order_id": "169819",
            "oar_billing_lastname": "Shotter",
            "oar_type": "email",
            "oar_email": "mikeshotter@hotmail.com",
            "oar_zip": "",
            "form_key": "kaqvShah7EsU2zEd"
        }
    }
]
************************************
[E_ERROR] Uncaught Error: Call to a member function setProductItem() on boolean in var/view_preprocessed/pub/static/app/design/frontend/MageSuper/magestylish/Magento_Sales/templates/order/items.phtml:1
Stack trace:
#0 vendor/magento/framework/View/TemplateEngine/Php.php(59): include()
#1 vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Sales\Block\Order\Items\Interceptor), '/var/www/sites/...', Array)
#2 vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callParent('render', Array)
#3 vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\TemplateEngine\Php\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Sales\Block\Orde
File: var/view_preprocessed/pub/static/app/design/frontend/MageSuper/magestylish/Magento_Sales/templates/order/items.phtml
Line: 1
```

**Comment by dmitry-fedyuk** [comment]
![03](https://user-images.githubusercontent.com/83204/112935150-00601580-9145-11eb-8aa1-179797d60170.png)
